name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install anyscale ray prefect prefect_ray s3fs
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::959243851260:role/github-action-prefect-integration
          role-session-name: s3access
          aws-region: us-west-2
      - name: Test Prefect <> Anyscale Integration
        env:
          ANYSCALE_HOST: ${{ secrets.ANYSCALE_HOST }}
          ANYSCALE_CLI_TOKEN: ${{ secrets.ANYSCALE_CLI_TOKEN }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        run: |
          pip install -e .
          envsubst < ci/prefect-agent-service-ci.yaml > /tmp/prefect-agent-service.out
          anyscale service deploy /tmp/prefect-agent-service.out
          PYTHONPATH=$PYTHONPATH:. python ci/submit_prefect_run_and_check.py
          PYTHONPATH=$PYTHONPATH:. python ci/test_ray_job_integration.py
