name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install anyscale ray prefect prefect_ray
      - name: Test Prefect <> Anyscale Integration
        env:
          ANYSCALE_HOST: ${{ secrets.ANYSCALE_HOST }}
          ANYSCALE_CLI_TOKEN: ${{ secrets.ANYSCALE_CLI_TOKEN }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        run: |
          envsubst < prefect-agent-service.yaml > prefect-agent-service.out
          anyscale service deploy prefect-agent-service.out
	  prefect deployment build prefect_test.py -n prefect_test -q test --infra-block anyscale-infra
	  prefect deployment apply main-deployment.yaml
